---
#@ load("hours.lib.yml", "Pivotal_US", "Pivotal_CA_Ontario", "SAP_DE_Walldorf")
delegatebot:
  watch:
  - target: { channel: &bosh C02HPPYQ2 }
  - target: { channel: &boshcoredev C094QRLEQ }
  delegate:
    union:
    - if:
        when:
        - or:
          - #@ Pivotal_US("America/Los_Angeles")
          - #@ Pivotal_CA_Ontario("America/Toronto")
        then:
          literalmap:
            from:
              pairist:
                team: bosh-director
                role: Interrupt
            users:
              Charles: U03RC8WQ6
              Rebecca: U8YCN97Q9
              Belinda: U5EJ8MQUW
              Miguel: UD46WTA4Q
              Morgan: U04V9L81Y
              Maya: U03DX27U9
              Jim: U02QZ1E3G
    - if:
        when:
        - #@ SAP_DE_Walldorf()
        then:
          literalmap:
            from:
              pairist:
                team: bosh-europe
                role: interrupt
            users:
              Beyhan: U0D8E67LZ
              David: U66SLUVQC
              Denis: UAQ9C5YSH
              Florian: U6HHKKQNT
              Kai: U6H6QCECD
              Max: U6GCKEN9H
              Sebastian: U8MRYTRHU
              Vladimir: UCZCG5L84
  options:
    empty_message: Sorry, no interrupt is available right now. The community may be able to help, or feel free to ping again later.
