---
jobs:
- name: test
  serial: true
  plan:
  - aggregate:
    - get: repo
      trigger: true
  - task: unit-tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: golang
          tag: 1.11.4-stretch
      inputs:
      - name: repo
        path: src/github.com/dpb587/slack-delegate-bot
      run:
        path: bash
        args:
        - -c
        - |
          set -eu
          export GOPATH=$PWD
          export PATH=$GOPATH/bin:$PATH
          cd src/github.com/dpb587/slack-delegate-bot
          go install ./vendor/github.com/onsi/ginkgo/ginkgo
          ./bin/test-unit
- name: deploy
  serial: true
  plan:
  - aggregate:
    - get: repo
      passed: [test]
      trigger: true
  - task: build-app
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: golang
          tag: 1.11.4-stretch
      inputs:
      - name: repo
        path: src/github.com/dpb587/slack-delegate-bot
      outputs:
      - name: app
      run:
        path: bash
        args:
        - -c
        - |
          set -eu
          export GOPATH=$PWD
          task_dir=$PWD
          cd src/github.com/dpb587/slack-delegate-bot
          go build -o app/cloudfoundry/bot ./delegatebot/main
          cp -rp app/cloudfoundry/. $task_dir/app
          wget -O $task_dir/app/ytt https://github.com/k14s/ytt/releases/download/v0.9.0/ytt-linux-amd64
          echo "f1bccd1dcc3410099f883d9d7ba91bf49f0b096202af9c114d7450028a96c24b  $task_dir/app/ytt" | shasum -c
          chmod +x $task_dir/app/ytt
  - put: cf-app
    params:
      # current_app_name: ((app_name)) # https://github.com/concourse/cf-resource/issues/62
      manifest: app/cf.yml
      path: app
      vars:
        slack_token: ((slack_token))
  - put: "deploy-status"
    params: { state: "success", commit: "repo" }
resources:
- name: repo
  type: git
  source:
    uri: https://github.com/dpb587/slack-delegate-bot.git
    branch: master
- name: cf-app
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: ((app_username))
    password: ((app_password))
    organization: ((app_organization))
    space: ((app_space))
- name: deploy-status
  type: github-status
  source:
    repository: dpb587/slack-delegate-bot
    access_token: ((github_access_token))
    context: deployed
resource_types:
- name: "github-status"
  type: "docker-image"
  source:
    repository: "dpb587/github-status-resource"
    tag: "master"
