#@ weekdays = [ "Mon", "Tue", "Wed", "Thu", "Fri" ]

#@ def Pivotal_US(tz):
and:
- hours:
    tz: #@ tz
    start: 09:00
    end: 18:00
- day:
    tz: #@ tz
    days: #@ weekdays
- not:
    date:
      tz: #@ tz
      dates:
      - 2019-01-01
      - 2019-01-21
      - 2019-02-18
      - 2019-05-27
      - 2019-07-04
      - 2019-09-02
      - 2019-11-28
      - 2019-11-29
      - 2019-12-25
#@ end

#@ def Pivotal_CA_Ontario(tz):
and:
- hours:
    tz: #@ tz
    start: 09:00
    end: 18:00
- day:
    tz: #@ tz
    days: #@ weekdays
- not:
    date:
      tz: #@ tz
      dates:
      - 2019-01-01
      - 2019-02-18
      - 2019-04-19
      - 2019-05-20
      - 2019-07-01
      - 2019-08-05
      - 2019-09-02
      - 2019-10-14
      - 2019-12-25
      - 2019-12-26
#@ end

#@ def SAP_DE_Walldorf():
and:
- hours:
    tz: Europe/Berlin
    start: 09:00
    end: 18:00
- day:
    tz: Europe/Berlin
    days: #@ weekdays
- not:
    date:
      tz: Europe/Berlin
      dates:
      - 2019-01-01
      - 2019-01-06
      - 2019-04-19
      - 2019-04-22
      - 2019-05-01
      - 2019-05-30
      - 2019-06-10
      - 2019-06-20
      - 2019-10-03
      - 2019-10-31
      - 2019-11-01
      - 2019-12-25
      - 2019-12-26
#@ end
